// Technology fingerprints. Each check is evidence from the page itself: response headers, cookies,
// <meta name="generator">, script/link URLs, or markup. `v` captures a version where one is exposed.
// Keep patterns specific: a false positive is worse than a miss.

export const SIGNATURES = [
  // CMS
  {name: 'WordPress', cat: 'CMS', meta: /WordPress ?([\d.]+)?/i, src: /\/wp-(?:content|includes)\//i, html: /<link[^>]+wp-json/i},
  {name: 'Drupal', cat: 'CMS', meta: /Drupal ?([\d.]+)?/i, header: {'x-generator': /Drupal/i, 'x-drupal-cache': /./}, src: /\/sites\/(?:default|all)\/(?:files|modules|themes)\//i},
  {name: 'Joomla', cat: 'CMS', meta: /Joomla!? ?([\d.]+)?/i, src: /\/media\/jui\//i},
  {name: 'Ghost', cat: 'CMS', meta: /Ghost ?([\d.]+)?/i, header: {'x-ghost-cache-status': /./}},
  {name: 'Wix', cat: 'Website builder', meta: /Wix\.com/i, header: {'x-wix-request-id': /./}, src: /static\.parastorage\.com|static\.wixstatic\.com/i},
  {name: 'Squarespace', cat: 'Website builder', html: /Static\.SQUARESPACE_CONTEXT|<!-- This is Squarespace\. -->/i, src: /static1\.squarespace\.com|assets\.squarespace\.com/i},
  {name: 'Webflow', cat: 'Website builder', meta: /Webflow/i, html: /data-wf-(?:page|site)=/i, src: /assets\.website-files\.com|cdn\.prod\.website-files\.com/i},
  {name: 'Framer', cat: 'Website builder', meta: /Framer ?([\w.]+)?/i, src: /framerusercontent\.com|framer\.com\/m\//i},
  {name: 'Weebly', cat: 'Website builder', src: /editmysite\.com/i},
  {name: 'HubSpot CMS', cat: 'CMS', meta: /HubSpot/i, header: {'x-hs-hub-id': /./}},
  {name: 'Contentful', cat: 'Headless CMS', src: /images\.ctfassets\.net|cdn\.contentful\.com/i},
  {name: 'Sanity', cat: 'Headless CMS', src: /cdn\.sanity\.io/i},
  {name: 'Strapi', cat: 'Headless CMS', header: {'x-powered-by': /Strapi/i}},
  {name: 'Adobe Experience Manager', cat: 'CMS', src: /\/etc\.clientlibs\//i},
  {name: 'Sitecore', cat: 'CMS', src: /\/-\/media\//i, cookie: /^SC_ANALYTICS_GLOBAL_COOKIE/i},
  {name: 'TYPO3', cat: 'CMS', meta: /TYPO3 ?([\d.]+)?/i, src: /\/typo3(?:conf|temp)\//i},
  // E-commerce
  {name: 'Shopify', cat: 'E-commerce', header: {'x-shopid': /./, 'x-shopify-stage': /./}, src: /cdn\.shopify\.com/i, html: /Shopify\.theme|window\.Shopify\b/i},
  {name: 'WooCommerce', cat: 'E-commerce', src: /\/wp-content\/plugins\/woocommerce\//i, html: /woocommerce-(?:page|no-js)|class="[^"]*\bwoocommerce\b/i, implies: ['WordPress']},
  {name: 'Magento', cat: 'E-commerce', src: /\/static\/version\d+\/frontend\/|mage\/cookies/i, cookie: /^mage-/i, html: /Magento_(?:Ui|Theme)/i},
  {name: 'BigCommerce', cat: 'E-commerce', src: /cdn\d*\.bigcommerce\.com/i},
  {name: 'PrestaShop', cat: 'E-commerce', meta: /PrestaShop/i, html: /var prestashop\s*=/i},
  {name: 'Salesforce Commerce Cloud', cat: 'E-commerce', src: /demandware\.static|\/on\/demandware\.store\//i},
  {name: 'Ecwid', cat: 'E-commerce', src: /app\.ecwid\.com/i},
  {name: 'OpenCart', cat: 'E-commerce', html: /index\.php\?route=(?:common|product)\//i},
  // JavaScript frameworks
  {name: 'Next.js', cat: 'JavaScript framework', header: {'x-powered-by': /Next\.js ?([\d.]+)?/i}, html: /<script[^>]+id="__NEXT_DATA__"|\/_next\/static\//i, implies: ['React']},
  {name: 'Nuxt', cat: 'JavaScript framework', html: /window\.__NUXT__|\/_nuxt\//i, implies: ['Vue.js']},
  {name: 'Gatsby', cat: 'Static site generator', meta: /Gatsby ?([\d.]+)?/i, html: /id="___gatsby"/i, implies: ['React']},
  {name: 'React', cat: 'JavaScript library', html: /data-reactroot|data-reactid|react(?:-dom)?(?:\.production)?(?:\.min)?\.js/i},
  {name: 'Vue.js', cat: 'JavaScript library', html: /data-v-[0-9a-f]{8}|vue(?:\.runtime)?(?:\.global)?(?:\.prod)?(?:\.min)?\.js/i},
  {name: 'Angular', cat: 'JavaScript framework', html: /\bng-version="([\d.]+)"/i},
  {name: 'AngularJS', cat: 'JavaScript framework', html: /\bng-app=|angular(?:\.min)?\.js/i},
  {name: 'Svelte', cat: 'JavaScript framework', html: /class="[^"]*\bsvelte-[a-z0-9]{6}\b/i},
  {name: 'SvelteKit', cat: 'JavaScript framework', html: /__sveltekit_|\/_app\/immutable\//i, implies: ['Svelte']},
  {name: 'Remix', cat: 'JavaScript framework', html: /window\.__remixContext/i, implies: ['React']},
  {name: 'Astro', cat: 'Static site generator', meta: /Astro v?([\d.]+)?/i, html: /<astro-island/i},
  {name: 'Hugo', cat: 'Static site generator', meta: /Hugo ([\d.]+)/i},
  {name: 'Jekyll', cat: 'Static site generator', meta: /Jekyll v?([\d.]+)?/i},
  {name: 'jQuery', cat: 'JavaScript library', src: /jquery(?:[.-]([\d.]+))?(?:\.min)?\.js/i},
  {name: 'Alpine.js', cat: 'JavaScript library', html: /\bx-data=["']/i, src: /alpinejs/i},
  {name: 'htmx', cat: 'JavaScript library', src: /htmx(?:\.org)?(?:\.min)?\.js/i, html: /\bhx-(?:get|post)=/i},
  {name: 'Bootstrap', cat: 'CSS framework', src: /bootstrap(?:\.bundle)?(?:\.min)?\.(?:css|js)/i},
  {name: 'Tailwind CSS', cat: 'CSS framework', src: /cdn\.tailwindcss\.com/i, html: /class="[^"]*\b(?:flex|grid) [^"]*\b(?:px|py|mt|mb)-\d+\b[^"]*\b(?:text|bg)-(?:gray|slate|zinc|neutral)-\d{2,3}\b/},
  {name: 'Font Awesome', cat: 'Font', src: /font-?awesome|kit\.fontawesome\.com/i},
  {name: 'Google Fonts', cat: 'Font', src: /fonts\.googleapis\.com|fonts\.gstatic\.com/i},
  {name: 'Adobe Fonts', cat: 'Font', src: /use\.typekit\.net/i},
  // Servers, languages, hosting, CDN
  {name: 'Nginx', cat: 'Web server', header: {server: /nginx(?:\/([\d.]+))?/i}},
  {name: 'Apache', cat: 'Web server', header: {server: /Apache(?:\/([\d.]+))?/i}},
  {name: 'Microsoft IIS', cat: 'Web server', header: {server: /Microsoft-IIS(?:\/([\d.]+))?/i}},
  {name: 'LiteSpeed', cat: 'Web server', header: {server: /LiteSpeed/i}},
  {name: 'Caddy', cat: 'Web server', header: {server: /Caddy/i}},
  {name: 'PHP', cat: 'Programming language', header: {'x-powered-by': /PHP(?:\/([\d.]+))?/i}, cookie: /^PHPSESSID$/},
  {name: 'ASP.NET', cat: 'Web framework', header: {'x-powered-by': /ASP\.NET/i, 'x-aspnet-version': /([\d.]+)/}, cookie: /^ASP\.NET_SessionId$/i},
  {name: 'Express', cat: 'Web framework', header: {'x-powered-by': /^Express$/i}},
  {name: 'Ruby on Rails', cat: 'Web framework', meta: /Ruby on Rails/i, cookie: /^_[a-z0-9_]+_session$/, html: /<meta name="csrf-param" content="authenticity_token"/i},
  {name: 'Django', cat: 'Web framework', cookie: /^csrftoken$/, html: /name="csrfmiddlewaretoken"/i},
  {name: 'Laravel', cat: 'Web framework', cookie: /^laravel_session$|^XSRF-TOKEN$/},
  {name: 'Cloudflare', cat: 'CDN', header: {server: /cloudflare/i, 'cf-ray': /./}},
  {name: 'Fastly', cat: 'CDN', header: {'x-served-by': /cache-[a-z]+\d+/i, 'x-fastly-request-id': /./}},
  {name: 'Akamai', cat: 'CDN', header: {'x-akamai-transformed': /./, server: /AkamaiGHost/i}},
  {name: 'Amazon CloudFront', cat: 'CDN', header: {'x-amz-cf-id': /./, via: /CloudFront/i}},
  {name: 'Amazon S3', cat: 'Hosting', header: {server: /AmazonS3/i}},
  {name: 'Vercel', cat: 'Hosting', header: {server: /Vercel/i, 'x-vercel-id': /./}},
  {name: 'Netlify', cat: 'Hosting', header: {server: /Netlify/i, 'x-nf-request-id': /./}},
  {name: 'GitHub Pages', cat: 'Hosting', header: {server: /GitHub\.com/i}},
  {name: 'Heroku', cat: 'Hosting', header: {via: /vegur/i}},
  {name: 'Google Cloud', cat: 'Hosting', header: {server: /Google Frontend/i, via: /google/i}},
  {name: 'WP Engine', cat: 'Hosting', header: {'x-powered-by': /WP Engine/i}},
  {name: 'Kinsta', cat: 'Hosting', header: {'x-kinsta-cache': /./}},
  {name: 'Varnish', cat: 'Cache', header: {via: /varnish/i, 'x-varnish': /./}},
  {name: 'HSTS', cat: 'Security', header: {'strict-transport-security': /./}},
  // Analytics and tags
  {name: 'Google Analytics', cat: 'Analytics', src: /google-analytics\.com\/(?:ga|analytics)\.js|googletagmanager\.com\/gtag\/js\?id=G-/i, html: /gtag\(['"]config['"],\s*['"](?:G|UA)-/i},
  {name: 'Google Tag Manager', cat: 'Tag manager', src: /googletagmanager\.com\/gtm\.js/i, html: /GTM-[A-Z0-9]{4,}/},
  {name: 'Google Ads', cat: 'Advertising', html: /gtag\(['"]config['"],\s*['"]AW-|googleadservices\.com/i},
  {name: 'Meta Pixel', cat: 'Advertising', src: /connect\.facebook\.net\/[^"']+\/fbevents\.js/i, html: /fbq\(['"]init['"]/i},
  {name: 'TikTok Pixel', cat: 'Advertising', src: /analytics\.tiktok\.com/i},
  {name: 'LinkedIn Insight Tag', cat: 'Advertising', src: /snap\.licdn\.com\/li\.lms-analytics/i, html: /_linkedin_partner_id/i},
  {name: 'X (Twitter) Pixel', cat: 'Advertising', src: /static\.ads-twitter\.com\/uwt\.js/i},
  {name: 'Microsoft Advertising', cat: 'Advertising', src: /bat\.bing\.com\/bat\.js/i},
  {name: 'Pinterest Tag', cat: 'Advertising', src: /s\.pinimg\.com\/ct\/core\.js/i},
  {name: 'Hotjar', cat: 'Analytics', src: /static\.hotjar\.com/i, html: /hjid\s*:/i},
  {name: 'Microsoft Clarity', cat: 'Analytics', src: /clarity\.ms\/tag/i},
  {name: 'Plausible', cat: 'Analytics', src: /plausible\.io\/js/i},
  {name: 'Fathom', cat: 'Analytics', src: /cdn\.usefathom\.com/i},
  {name: 'Matomo', cat: 'Analytics', src: /matomo\.js|piwik\.js/i, html: /_paq\.push/},
  {name: 'Mixpanel', cat: 'Analytics', src: /cdn\.mxpnl\.com|mixpanel-\d/i},
  {name: 'Segment', cat: 'Customer data platform', src: /cdn\.segment\.com\/analytics\.js/i},
  {name: 'Amplitude', cat: 'Analytics', src: /cdn\.amplitude\.com/i},
  {name: 'Heap', cat: 'Analytics', src: /cdn\.heapanalytics\.com/i},
  {name: 'PostHog', cat: 'Analytics', src: /posthog/i, html: /posthog\.init\(/},
  {name: 'Vercel Analytics', cat: 'Analytics', src: /\/_vercel\/insights\/script\.js/i},
  {name: 'Cloudflare Web Analytics', cat: 'Analytics', src: /static\.cloudflareinsights\.com\/beacon/i},
  // Marketing, CRM, chat, support
  {name: 'HubSpot', cat: 'Marketing automation', src: /js\.hs-scripts\.com|js\.hsforms\.net|js\.hs-analytics\.net/i},
  {name: 'Mailchimp', cat: 'Email marketing', src: /chimpstatic\.com|list-manage\.com/i},
  {name: 'Klaviyo', cat: 'Email marketing', src: /static\.klaviyo\.com|klaviyo\.com\/onsite/i},
  {name: 'Marketo', cat: 'Marketing automation', src: /munchkin\.marketo\.net/i},
  {name: 'Pardot', cat: 'Marketing automation', src: /pi\.pardot\.com/i},
  {name: 'ActiveCampaign', cat: 'Email marketing', src: /trackcmp\.net/i},
  {name: 'Intercom', cat: 'Live chat', src: /widget\.intercom\.io|js\.intercomcdn\.com/i},
  {name: 'Drift', cat: 'Live chat', src: /js\.driftt\.com/i},
  {name: 'Zendesk', cat: 'Customer support', src: /static\.zdassets\.com/i},
  {name: 'Tawk.to', cat: 'Live chat', src: /embed\.tawk\.to/i},
  {name: 'Crisp', cat: 'Live chat', src: /client\.crisp\.chat/i},
  {name: 'LiveChat', cat: 'Live chat', src: /cdn\.livechatinc\.com/i},
  {name: 'Tidio', cat: 'Live chat', src: /code\.tidio\.co/i},
  {name: 'Freshchat', cat: 'Live chat', src: /wchat\.freshchat\.com/i},
  {name: 'Calendly', cat: 'Scheduling', src: /assets\.calendly\.com/i},
  {name: 'Typeform', cat: 'Forms', src: /embed\.typeform\.com/i},
  // Payments
  {name: 'Stripe', cat: 'Payments', src: /js\.stripe\.com/i},
  {name: 'PayPal', cat: 'Payments', src: /paypal\.com\/sdk\/js|paypalobjects\.com/i},
  {name: 'Klarna', cat: 'Payments', src: /klarna(?:cdn|services)?\.(?:com|net)/i},
  {name: 'Afterpay', cat: 'Payments', src: /afterpay\.com|static\.afterpay/i},
  {name: 'Shop Pay', cat: 'Payments', html: /shop-pay-(?:button|installments)|shopify-payment-button/i, implies: ['Shopify']},
  // Consent, security, misc
  {name: 'OneTrust', cat: 'Cookie consent', src: /cdn\.cookielaw\.org|optanon/i},
  {name: 'Cookiebot', cat: 'Cookie consent', src: /consent\.cookiebot\.com/i},
  {name: 'CookieYes', cat: 'Cookie consent', src: /cdn-cookieyes\.com/i},
  {name: 'reCAPTCHA', cat: 'Security', src: /google\.com\/recaptcha|gstatic\.com\/recaptcha/i},
  {name: 'hCaptcha', cat: 'Security', src: /hcaptcha\.com\/1\/api\.js/i},
  {name: 'Cloudflare Turnstile', cat: 'Security', src: /challenges\.cloudflare\.com\/turnstile/i},
  {name: 'Sentry', cat: 'Error tracking', src: /browser\.sentry-cdn\.com|js\.sentry-cdn\.com/i},
  {name: 'New Relic', cat: 'Monitoring', html: /NREUM|js-agent\.newrelic\.com/},
  {name: 'Datadog RUM', cat: 'Monitoring', src: /datadoghq-browser-agent|browser-intake-datadoghq/i},
  {name: 'Optimizely', cat: 'A/B testing', src: /cdn\.optimizely\.com/i},
  {name: 'VWO', cat: 'A/B testing', src: /dev\.visualwebsiteoptimizer\.com/i, html: /_vwo_code/},
  {name: 'YouTube embed', cat: 'Video', src: /youtube\.com\/embed\/|youtube-nocookie\.com\/embed/i},
  {name: 'Vimeo embed', cat: 'Video', src: /player\.vimeo\.com\/video/i},
  {name: 'Wistia', cat: 'Video', src: /fast\.wistia\.(?:com|net)/i},
  {name: 'Google Maps', cat: 'Maps', src: /maps\.googleapis\.com\/maps\/api\/js|google\.com\/maps\/embed/i},
  {name: 'Mapbox', cat: 'Maps', src: /api\.mapbox\.com\/mapbox-gl-js/i},
  {name: 'jsDelivr', cat: 'CDN', src: /cdn\.jsdelivr\.net/i},
  {name: 'cdnjs', cat: 'CDN', src: /cdnjs\.cloudflare\.com/i},
  {name: 'unpkg', cat: 'CDN', src: /unpkg\.com/i},
  {name: 'Trustpilot widget', cat: 'Reviews', src: /widget\.trustpilot\.com/i},
  {name: 'Yotpo', cat: 'Reviews', src: /staticw2\.yotpo\.com|cdn-widgetsrepository\.yotpo\.com/i},
  {name: 'Judge.me', cat: 'Reviews', src: /judge\.me/i},
  {name: 'Algolia', cat: 'Search', src: /algolia(?:net|search)?\.(?:com|net)|algoliasearch/i},
  {name: 'PWA manifest', cat: 'Progressive web app', html: /<link[^>]+rel=["']manifest["']/i}
];
